version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: always
    env_file:
      - db.env
    ports:
      - "4445:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db-net

  db-admin:
    image: dpage/pgadmin4
    env_file:
      - db-admin.env
    ports:
      - "4446:80"
    depends_on:
      - db
    networks:
      - db-net

volumes:
  db-data:

networks:
  db-net:
    driver: bridge