version: '3.8'

services:
  db:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .db-prod.env
    ports:
      - "4445:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db-net

  db-admin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .db-admin.env
    ports:
      - "4446:80"
    depends_on:
      - db
    networks:
      - db-net

  backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - .backend-prod.env
    depends_on:
      - db

  webserver:
    build: ./app-webserver
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  db-data:

networks:
  db-net:
    driver: bridge